[package]
name = "bazaar-vault"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "bazaar_vault"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
