FROM node:22-alpine AS builder
WORKDIR /app
ENV HUSKY=0
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install --ignore-scripts
RUN npx prisma generate
COPY . .

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/bazaar_relayer.ts ./bazaar_relayer.ts
COPY --from=builder /app/lib ./lib

CMD ["npx", "tsx", "bazaar_relayer.ts"]
