[package]
name = "bazaar-beacon"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "22.0.11", default-features = false }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
panic = "abort"
codegen-units = 1
lto = true

[workspace]
